name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: barrouh/maven-settings
        ref: refs/heads/master
        token: ${{secrets.ACCESS_TOKEN}}
